<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>let命令-基本用法</title>
</head>
<body>
<script type="text/javascript">
    console.log('---let和var---');
    /*
        ES6新增了let命令，用来声明变量。用法类似于var，但是所声明的变量，
        只在let命令所在的代码块内有效
        分别用let和var声明了两个遍历，结果，变量a报错，变量b输出正确结果，
        这表明let声明的变量只在其所在的代码块内有效。
    */
    {
        let a = 10;
        var b = 1;
    }
    try {
        console.log(a);
    } catch (e) {
        // ReferenceError: a is not defined.
        console.error(e);
    }
    // 1
    console.log(b);

    /* ------------------------------------------------------------------------ */
    console.log('---计数器---');
    /* 计数器 */
    /*
        变量i是var命令声明的，在全局范围内有效，所以全局只有一个变量i,
        每次循环，变量i的值都会发生变化，而循环内被赋给数组arr的函数内部的
        console.log(i)，里面的i指向的就是全局的i，所有arr的成员里面的i，
        指向的都是同一个i，导致运行时输出的是最后一轮的i，就是10
    */
    var arr = [];
    for (var i = 0; i < 10; i++) {
        arr[i] = function() {
            console.log(i);
        }
    }
    arr[6]();
    /*
        变量i是let声明的，当前的i只在本轮循环内有效，所以每一次循环i其实
        都是一个新的变量，所以最后输出的是i。问题是，如果每一轮循环的变量i
        都是重新声明的，那它怎么知道上一轮的值，从而计算本轮循环的值？因为
        js引擎内部会记住上一轮循环的值，初始化本轮的变量i时，就在上一轮循环
        的基础上进行计算。
    */
    for (let i = 0; i < 10; i++) {
        arr[i] = function() {
            console.log(i);
        }
    }
    arr[6]();
    /*
        for循环有一个特性，就是设置循环变量的部分是一个父作用域，
        而循环体内部是一个单独的子作用域
    */
    for (let i = 0; i < 3; i++) {
        // 循环体内部的i和循环变量的i不在同一个作用域
        let i = 'abc';
        console.log(i);
    }

    /* ------------------------------------------------------------------------ */
    console.log('---变量提升---');
    /* 变量提升 */
    /*
        var命令会发生“变量提升”现象，即变量可以在声明之前使用，值为undefined。
        为了纠正这种现象，let命令改变了语法行为，它所声明的变量一定要在声明后
        使用，否则报错。
    */
    // undefined
    console.log(foo);
    var foo = 'foo';

    try {
        console.log(bar);
    } catch (e) {
        // ReferenceError: bar is not defined
        console.error(e);
    }
    let bar = 'bar';

    /* ------------------------------------------------------------------------ */
    console.log('---暂时性死区---');
    /* 暂时性死区 */
    /*
        只要块级作用域内存在let命令，它所声明的变量就绑定这个区域，不再
        受外部影响。
        var tmp为全局变量，但块级作用域内let又声明了一个局部变量tmp，导致
        后者绑定这个块级作用域，所以在let声明变量前，对tmp赋值报错。
        ES6明确规定，若区块内存在let或const命令，这个区块对这些命令声明的
        变量，一开始就形成了封闭作用域。凡是在声明之前就使用这些变量，会报错。
        总之，在代码块内，使用let命令声明变量之前，该变量都是不可用的。这在
        语法上，称为“暂时性死区”(temporal dead zone 简称TDZ)
    */
    var tmp = 123;
    if (true) {
        try {
            tmp = 'abc';
        } catch (e) {
            // ReferenceError: tmp is not defined
            console.error(e);
        }
        let tmp;
    }
    /*
        在let命令声明变量tmp之前，都属于变量tmp的死区
    */
    if (true) {
        try {
            tmp = 'abc';
            console.log(tmp);
        } catch (e) {
            // ReferenceError: tmp is not defined
            console.error(e);
        }

        let tmp;
        // undefined
        console.log(tmp);

        tmp = 123;
        // 123
        console.log(tmp);
    }
    /*
        暂时性死区，也意味着typeof不再是一个百分百的安全操作。
        若一个变量根本没有被声明，undeclared_variable没有被声明，使用typeof反而不报错。
        所以，在没有let前，typeof运算符是百分百安全的。永远不会报错。现在这一点不成立了。
    */
    {
        try {
            console.log(typeof x);
        } catch (e) {
            // ReferenceError: x is not defined
            console.error(e);
        }
        // undefined
        console.log(typeof undeclared_variable);
        let x;
    }
    /* 有些死区不太容易被发现 */
    var fooFun = function(x = y, y = 2) {
        console.log([x, y]);
        return [x, y]; // 报错
    };

    var barFun = function(x = 2, y = x) {
        console.log([x, y]);
        return [x, y]; // [2, 2]
    };

    try {
        fooFun();
    } catch (e) {
        console.error(e);
    }
    barFun();
    /*
        使用let声明变量时，只要变量在还没有声明完成前使用，
        就会报错。
        在变量x的声明语句还没有执行完成前，就去取x的值，导致x未定义
    */
    {
        // 不报错
        var x = x;
        try {
            let x = x;
        } catch (e) {
            // ReferenceError: x is not defined
            console.error(e);
        }
    }

    /* ------------------------------------------------------------------------ */
    console.log('---不允许重复声明---');
    /* 不允许重复声明 */
    /*
        let不允许在相同作用域内，重复声明同一个变量
    */
    function func_a() {
        var fun_a = 1;
        let fun_a = 10;
    }

    function func_b() {
        let fun_b = 10;
        let fun_b = 1;
    }

    try {
        func_a();
    } catch (e) {
        // Identifier 'fun_a' has already been declared
        console.error(e);
    }

    try {
        func_b();
    } catch (e) {
        // Identifier 'fun_b' has already been declared
        console.error(e);
    }
    /*
        不能在函数内部重新声明参数
    */
    function func_c(arg) {
        let arg;
    }

    try {
        func_c();
    } catch (e) {
        // Identifier 'arg' has already been declared
        console.error(e);
    }

    // 不报错
    function func_d(arg) {
        {
            let arg;
            console.log(arg)
        }
    }

    func_d();
</script>
</body>
</html>